# Generated by Django 5.0.4 on 2024-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
